name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm turbo run build --filter=app

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: apps/app/.next

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          API_URL: https://api.fantasycraft.io
          NEXTAUTH_URL: https://fantasycraft.io
          PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK: true
        with:
          host: 89.116.51.219
          port: 22
          username: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          scp_source: apps/app
          scp_target: /root/dev/fantasy-craft
          after_script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Navigate to the project directory
            cd /root/dev/fantasy-craft

            pm2 start npm --name "app" -- start --cwd . --env NODE_ENV=production --env NEXTAUTH_URL=https://fantasycraft.io --env PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK=true
