name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.116.51.219 << 'EOF'
            cd /root/dev/fantasy-craft
            # Ensure pnpm and pm2 are installed
            if ! command -v pnpm &> /dev/null
            then
              npm install -g pnpm
            fi
            if ! command -v pm2 &> /dev/null
            then
              npm install -g pm2
            fi
            git pull origin main
            pnpm install
            pnpm turbo build --filter=api --filter=app
            pm2 restart all
          EOF
