name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 89.116.51.219
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/dev/fantasy-craft
            git pull origin main
            pnpm install
            pnpm turbo build --filter=api --filter=app
            pm2 restart all

      # - name: Deploy to production server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no root@89.116.51.219 << 'EOF'
      #       cd /root/dev/fantasy-craft
      #       git pull origin main
      #       pnpm install
      #       pnpm turbo build --filter=api --filter=app
      #       pm2 restart all
      #     EOF
