name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      # setup pm2
      - name: Install pm2
        run: |
          pnpm install pm2 -g

      - name: Deploy to production server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.116.51.219 << 'EOF'
            cd /root/dev/fantasy-craft
            git pull origin main
            pnpm install
            pnpm turbo build --filter=api --filter=app
            pm2 restart all
          EOF
