name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm turbo run build --filter=app
        if: success()

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        if: success()
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        with:
          host: 89.116.51.219
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # Navigate to the project directory
            cd /root/dev/fantasy-craft

            # Pull the latest changes from the repository
            git pull origin main

            pnpm install

            pnpm turbo build --filter=app

            pm2 start ecosystem.config.js --env production

            echo "Deployment successful"
