# name: Deploy to Production

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Setup SSH
#         uses: appleboy/ssh-action@v0.1.10
#         env:
#           DATABASE_URL: ${{ secrets.DATABASE_URL }}
#           NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
#         with:
#           host: 89.116.51.219
#           username: root
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           command_timeout: 30m
#           script: |
#             export NVM_DIR=~/.nvm
#             source ~/.nvm/nvm.sh

#             # Navigate to the project directory
#             cd /root/dev/fantasy-craft

#             # Backup the current app build
#             cp -r apps/app/.next ../backup_next
#             cp -r apps/app/node_modules ../backup_node_modules

#             # Pull the latest changes from the repository
#             git pull origin main

#             #pnpm install
#             #pnpm turbo build --filter=app
#             #pm2 start ecosystem.config.js --env production

#             # Attempt to build only the affected app
#             if pnpm install --frozen-lockfile && pnpm turbo run build --filter=app; then
#               echo "Build successful, proceeding with deployment"

#               pm2 reload ecosystem.config.js --env production

#               echo "Deployment successful"
#             else
#               echo "Build failed, rolling back to previous version"

#               # Restore backup if the build fails
#               cp -r ../backup_node_modules apps/app/node_modules
#               cp -r ../backup_next apps/app/.next

#               echo "Rollback successful, restarting the app"
#               pm2 reload ecosystem.config.js --env production
#             fi
